r"""Python based solvers for HE burn time for DSD verification problems.

This suite of solvers calculate HE burn times for DSD verification problems.

The DSD High Explosive Problem Set is a series of three problems
designed to test the burn table solution (HE light times) generated by DSD
level-set solvers for burn simulations. The Cylindrical Expansion test
problem has an exact burn time solution in 2D [Bdzil]_. The 2D Rate Stick
and Explosive Arc test problems can each be reduced to a quasi-linear PDE
for the shock-normal angle, which can be solved using highly-accurate
numerical methods. That solution must then be inverted to obtain the burn
time solution on the specified grid.

.. [Bdzil] Bdzil, J. B., R. J. Henninger, and J. W. Walter, Test Problems
   for DSD2D, LA-14277, 2006.

"""

from ratestick import RateStick
from cylexpansion import CylindricalExpansion
from explosivearc import ExplosiveArc
