image: "re-registry.lanl.gov/verification/python-3.11_ver_ci"

before_script:
  - python -V  # Print out python version for debugging
  - source /venv/bin/activate
  - export PYTHONPATH="${PYTHONPATH}:/venv/lib/python3.11/site-packages"
  - pip install --no-deps ./

ep_tests:
  stage: test
  script:
    - pytest --junitxml=report.xml --cov=exactpack.solvers exactpack/tests/
    - coverage xml
  coverage: /(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/
  artifacts:
    when: always
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
  tags:
    - turquoise
    - kubernetes
    - charm

teststyle:
  stage: test
  script:
    - sphinx-build -W -b html doc/source public
  tags:
  - charm
  - turquoise
  - kubernetes

pages:
  stage: deploy
  script:
    - sphinx-build -b html doc/source public
  artifacts:
    paths:
      - public
  only:
    - master
  tags:
  - charm
  - turquoise
  - kubernetes
